name: 打包前端项目

on: push
jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
     - name: 调用checkout读取仓库内容
       uses: actions/checkout@v4

     - name: 安装npm
       run: npm install
       
     - name: 打包项目
       run: npm run build
